name: CI — Lint & Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip

          # 1. Устанавливаем базовый бэкенд
          pip install -r requirements.txt

          # 2. Устанавливаем ML-зависимости (откуда подтянется numpy)
          pip install -r requerements-inference.txt
          
          # 3. Доустанавливаем инструменты самого тестирования
          pip install pytest httpx

          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt || true; fi
      - name: Run tests
        run: |
          pytest -q

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install and build UI
        working-directory: ui
        run: |
          npm ci
          npm run build
